[GCP_SERVICE_ACCOUNT]
type = "service_account"
project_id = "barbearia-dashboard"
private_key_id = "7c71bcbfaa1a8d935e1474fcabbe0c7c7ea8cae5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8pdM0rUTx9rd7
oMcbcthX0E3afkwp/+0eKKHxQ6vf2kB0QSmbsAD3415voXxUa+7c8B+eUoDNxNBM
LKRQGhwBZ1LAgNovSq6Xdr2mZNEWsONEbI92xqKqRi6d182uUa9JinOpHGrLa+Wh
tq6pfN1vC0NadVk48tv0w/OLbfqQtRvppfG2SvzHIUnxGm59ghpd5M+rPcAAIZmm
h5SHmAbEH7LNikuqmKpJRGpEmzPXtJWZ8JDIjTyeqmkG2KOxPsXIAfb7q6QVjWks
znPyKUaY+M2q2Pg8Isn+Ksu8OAbvxMJUK01p53HryszO6bUlaGD8vDAdHtETQyVI
S7gHfwmTAgMBAAECggEAMT4L4p0z+QEQpgmyz3xr8ogiOl1rXi864vtyQjsK21Tq
LC5yQPxxVEOafAMoJBVEdZGMf1RD4PJ1+NxSS8J0+vzQggVgbqXM6yaInK2GUqj7
ufmofTWecln9gyA4xT73RXgJduQ/EDhq6Yp5Dy7T0k+bVjp5fr8OIVcg9I1RsYHS
M4E05KiWD0NDS1Fm9Dp8FGEwVtczuwlCqSN8W5AIFtgfKFuTNq92jqPDXGosOx6p
QjGmADBeUwt1flxBlXaCy9QPh8h2OfVmUsU6G6cjAKRYFcopUypkjWPndvbbe3pO
MLxU/23ds6TqQpW72XP86hx15UxgxZ04SMuefn/dWQKBgQDhHndsubNEEHMfS6ZE
MKZE62R9XOgpYMa5RXf+WmduJ2CAk2pawDow2dXfUYLKfFSwAZ1Ip4OgxMn78yra
KSen3LBC4RtPoBQiCs35dSZPHfm8DiyAsv0ZDBC9NgfaNubo++cCCXfR1JgkJx7a
T/YraC+M2m2EiK/7D/1lqbyXjwKBgQDWhpe62K9x1+Wh1Ld1BjBsm2kZwRM2L9Le
EZEJyuVy7uZIpuBz2ib3hpee5RDFGclFq45nc9TSIveZJoITjQb3VdbtpSbBGIiz
wjCmxT4B4loWeTgCrAi1e7Ww7B9ZBwPdOFMNtgVUYHxFcoiKPxV7oNRoc/84Aovk
xNNHN0ALvQKBgQDMR2c7hC+GHh85UN5plnPqqmgf0kTh922dBcrjRooAzT6mrh6e
hzzGw4VuBntW3wfCR1TAbzHkm25mcLx8B0hy7LINnlO4J5zdX0yVh5bhyGOsIHiF
uOYu6mHuMK9jdtqGpL91e7387Ju6gr1egZzyurIbcMJct+RpQJNCw4ndRQKBgFYl
FBbe3oz7omW68rSWeKmUOr8xzhIrYCT2ruRcyoi9sFGqWWWMS6uIK6iN2Y8cjLti
abvXQrXjfsPMN927+vklSjqB4C8YOATfTQQbHoxJJd3ybXB9Pr4J4GscVnY8n+uc
q5VM65T3bc/Bb1z8ehb7/W+4bNtEAoMqGqF1aU2NAoGBAMNja2qMZboIvQYpaBZ4
POSlVPpbIkTs1MbQC8uEXJpyLNGk2Cl9V7b8vZ5+fMFP5Glj4gA+oi/feZEstwFG
4+7guUaM3uZX9Knbtva5Cg1LQW5b6kSCYyMcfMliWBmlauDmGdAqitWqM9PO0Se2
qvoBHZw/ZVfqTcpCdLROJUgm
-----END PRIVATE KEY-----"""
client_email = "streamlit-reader@barbearia-dashboard.iam.gserviceaccount.com"
client_id = "102292204018013167995"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-reader%40barbearia-dashboard.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[PLANILHA_URL]
url = "https://docs.google.com/spreadsheets/d/1qtOF1I7Ap4By2388ySThoVlZHbI3rAJv_haEcil0IUE/edit?usp=sharing"
